name: rspec

on:
  - pull_request

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      - env:
          RAILS_ENV: test
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: 2.6.6
      # Install your dependencies
      - run: cd server && gem install bundler && bundle install

      # Run ESLint
      - run: cd server && bundle exec rspec
