name: rspec

on:
  - pull_request

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    container:
      image: ruby:2.6.6
      env:
        RAILS_ENV: test
        RAILS_DATABASE_HOST: postgres # this is needed
        RAILS_DATABASE_USER: postgres
        RAILS_DATABASE_PASSWORD: password
    steps:
      # Check out the repository
      - uses: actions/checkout@v1
      # Install your dependencies
      - run: cd server && gem install bundler && bundle install
      # prepare server
      - run: cd server && bundle exec rake db:create
      # Run rspec
      - run: cd server && bundle exec rspec
